### ISSUE TITLE
Ansible variable naming

### ISSUE THREAD

**Issue by cianmawhinney** [cianmawhinney/homelab#78]
Didn't occur to me that variables could be nested under each other, could be an opportunity to refactor the vars file to have a hierarchy per service

**Comment by cianmawhinney** [comment]
This might still be of value, but I've run into a situation where it can't be used.

The following will fail as the service object isn't fully defined yet when service.url is evaluated:
```yaml
service:
  version: 1.0
  url: /something/{{ service.version }}/whatever
```
